export { default as Home } from './home';
export { default as About } from './about';
export { default as Stewardship } from './stewardship';
export { default as Browse } from './browse';
export { default as Blogs } from './blogs';
export { default as BlogDetails } from './blogDetail';
export { default as BrowseNaturalToursMain } from "./browseNaturalToursMain"
export { default as BrowseNwToursMain } from "./browseNwToursMain"
export { default as BrowseImageOfInterest } from "./browseImageOfInterest"
export { default as Cart } from "./cart"
export { default as Contact } from "./contact"
export { default as Payment } from "./payment"
export { default as ThankYou } from "./thankyou"
export { default as NatureTour } from './natureTour';
export { default as NwCollageTour } from './nwCollageTour';
export { default as InterestImagesTour } from './imagesTour';
export { default as Design } from './design';
export { default as ChooseLayout } from './ChooseLayout/chooseLayout';
export { default as CreateCollage } from './CreateCollage/createCollage';
export { default as DashboardSelectImages } from './dashboardSelectImages';
export { default as DashboardSelectLayout } from './dashboardSelectLayout';
export { default as DashboardAdjustSize } from './dashboardAdjustSize';
export { default as Login } from './login';
export { default as Register } from './register';
export { default as UserPanel } from './userAccount';
export { default as HomeThankYou } from './homeThankyou';
export { default as ProductDetail } from './productDetail';
export { default as ErrorPage } from './errorPage';
export { default as Refund } from "./refund";
export { default as Privacy } from "./privacyPolicy";
export { default as TermsCondition } from "./termCondition";
export { default as Support} from "./support"
export { default as ForgetPassword } from "./forget";
export { default as VerifyOTP } from "./verify";
export { default as PasswordChange } from "./changePassword";
export { default as OrderDetailSummary } from "./orderDetail";